dist: focal
language: node_js
node_js: 12
services:
  - docker

install:
  - npm ci
  - npm run develop

jobs:
  include:
    - stage: Tests
      name: Node
      script:
        - npm run mocha -- test-expensive/node.js
    - name: Contracts
      script:
        - npm run mocha -- test-expensive/contracts.js
    - name: Compatibility tests
      script:
        - npm run mocha -- test-expensive/compatibility-tests.js
    - name: Shape
      script:
        - npm run mocha -- test-expensive/shape-*.js
    - name: Other tests
      script:
        - npm run aetest
