version: 2
jobs:
  build:
    docker:
    - image: circleci/node:9.5.0
    branches:
      only:
        - update/migrate-to-circleci
          
    steps:
      - checkout

      - run:
          command: |
            #sudo rm /usr/local/bin/docker-compose
            sudo curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
            sudo chmod +x docker-compose
            sudo mv docker-compose /usr/local/bin
            sudo npm install -g lerna
            sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
            echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update -qq
            sudo apt-get install -y -qq yarn


      - run:
          command: |
            sudo npm install
            lerna bootstrap
            cd packages/aeproject-lib
            npm run tsc
            cd ../..
            sudo npm run develop

      # run tests!
      - run: aeproject --version
      - run:
          command: npm test
          no_output_timeout: 30m