version: '3'
services:
  node1:
    image: aeternity/aeternity:v5.3.0
    hostname: node1
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: |
      bin/aeternity console -noinput -aehttp enable_debug_endpoints true
    volumes:
      - './docker/aeternity_node1_mean15.yaml:/home/aeternity/aeternity.yaml'
      - './docker/keys/node1:/home/aeternity/node/keys'
  node2:
    image: aeternity/aeternity:v5.3.0
    hostname: node2
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: |
      bin/aeternity console -noinput -aehttp enable_debug_endpoints true
    volumes:
      - './docker/aeternity_node2_mean15.yaml:/home/aeternity/aeternity.yaml'
      - './docker/keys/node2:/home/aeternity/node/keys'
  node3:
    image: aeternity/aeternity:v5.3.0
    hostname: node3
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: |
      bin/aeternity console -noinput -aehttp enable_debug_endpoints true
    volumes:
      - './docker/aeternity_node3_mean15.yaml:/home/aeternity/aeternity.yaml'
      - './docker/keys/node3:/home/aeternity/node/keys'
  proxy:
    image: 'nginx:1.13.8'
    hostname: proxy
    ports:
      - '3001:3001'
      - '3002:3002'
      - '3003:3003'
    volumes:
      - './docker/nginx-default.conf:/etc/nginx/conf.d/default.conf'
      - './docker/nginx-cors.conf:/etc/nginx/cors.conf'
      - './docker/nginx-ws.conf:/etc/nginx/ws.conf'
volumes:
  node1_db: null
  node1_keys: null
  node2_db: null
  node2_keys: null
  node3_db: null
  node3_keys: null
